// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportTeService.Api.Data;

#nullable disable

namespace TransportTeService.Api.Migrations
{
    [DbContext(typeof(TransportDbContext))]
    [Migration("20251113162739_RestoreGuidsWithAutoGeneration")]
    partial class RestoreGuidsWithAutoGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransportTeService.Api.Models.LigneTransport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreePar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Declaration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LigneCommande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LivraisonPartielle")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiePar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NoLigne")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TransportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransportId");

                    b.ToTable("LignesTransports");
                });

            modelBuilder.Entity("TransportTeService.Api.Models.LigneTransportEval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Colisage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Commentaires")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreePar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Designation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("Devise")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LigneTransportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marque")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MarquesCollis")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("MasseBrute")
                        .HasColumnType("decimal(13,2)");

                    b.Property<decimal?>("MasseNette")
                        .HasColumnType("decimal(13,2)");

                    b.Property<Guid?>("ModeConditionnement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiePar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Nombre")
                        .HasColumnType("int");

                    b.Property<string>("NumerosCollis")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("Partenaire")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaysOrigine")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PositionTarifaire")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal?>("Quantite")
                        .HasColumnType("decimal(15,3)");

                    b.Property<Guid?>("UniteStatistique")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ValeurDevise")
                        .HasColumnType("decimal(18,5)");

                    b.Property<long?>("ValeurFCFA")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(15,3)");

                    b.HasKey("Id");

                    b.HasIndex("LigneTransportId")
                        .IsUnique();

                    b.ToTable("LignesTransportsEval");
                });

            modelBuilder.Entity("TransportTeService.Api.Models.Transport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ATA")
                        .HasColumnType("datetime2");

                    b.Property<string>("Assurance")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BAD_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("BAD_Ref")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Consignee")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreePar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateApurement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ETA")
                        .HasColumnType("datetime2");

                    b.Property<int>("Escale")
                        .HasColumnType("int");

                    b.Property<int>("Etat")
                        .HasColumnType("int");

                    b.Property<bool>("IdentiqueCommande")
                        .HasColumnType("bit");

                    b.Property<string>("ManifesteArrivee")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManifesteDepart")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MessageErreur")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiePar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NavireNom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoADV")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoAVE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoBESC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoConnaissement")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoTransport")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoVoyage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NotifierSMS")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PosteAttribue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TLUPE")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TransitaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransporteurMaritime")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NoTransport")
                        .IsUnique()
                        .HasFilter("[NoTransport] IS NOT NULL");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("TransportTeService.Api.Models.TransportEval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Assurance")
                        .HasColumnType("int");

                    b.Property<decimal?>("AssuranceDevise")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal?>("AssuranceFCFA")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal?>("AutresChargesDevise")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal?>("AutresChargesFCFA")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<int?>("BureauDedouanement")
                        .HasColumnType("int");

                    b.Property<string>("Commentaires")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Consignee")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreePar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DestinationFinale")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Devise")
                        .HasColumnType("int");

                    b.Property<string>("Expediteur")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("FretDevise")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal?>("FretFCFA")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<Guid?>("Incoterm")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MasseBrute")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<Guid?>("ModeConditionnement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ModeTransport")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiePar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("NbreUnite")
                        .HasColumnType("int");

                    b.Property<string>("Notifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("Partenaire")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PaysDestination")
                        .HasColumnType("int");

                    b.Property<Guid>("TransportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Transporteur")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UniteDeChargement")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValeurDevise")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<long?>("ValeurFCFA")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransportId")
                        .IsUnique();

                    b.ToTable("TransportsEval");
                });

            modelBuilder.Entity("TransportTeService.Api.Models.LigneTransport", b =>
                {
                    b.HasOne("TransportTeService.Api.Models.Transport", "Transport")
                        .WithMany("LignesTransport")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("TransportTeService.Api.Models.LigneTransportEval", b =>
                {
                    b.HasOne("TransportTeService.Api.Models.LigneTransport", "LigneTransport")
                        .WithOne("LigneTransportEval")
                        .HasForeignKey("TransportTeService.Api.Models.LigneTransportEval", "LigneTransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LigneTransport");
                });

            modelBuilder.Entity("TransportTeService.Api.Models.TransportEval", b =>
                {
                    b.HasOne("TransportTeService.Api.Models.Transport", "Transport")
                        .WithOne("TransportEval")
                        .HasForeignKey("TransportTeService.Api.Models.TransportEval", "TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("TransportTeService.Api.Models.LigneTransport", b =>
                {
                    b.Navigation("LigneTransportEval");
                });

            modelBuilder.Entity("TransportTeService.Api.Models.Transport", b =>
                {
                    b.Navigation("LignesTransport");

                    b.Navigation("TransportEval");
                });
#pragma warning restore 612, 618
        }
    }
}
